[project]
name = "uniface"
version = "1.1.0"
description = "UniFace: A Comprehensive Library for Face Detection, Recognition, Landmark Analysis, Age, and Gender Detection"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Yakhyokhuja Valikhujaev", email = "yakhyo9696@gmail.com" }
]
dependencies = [
    "numpy>=1.21.0",
    "opencv-python>=4.5.0",
    "onnx>=1.12.0",
    "onnxruntime>=1.16.0",
    "scikit-image>=0.19.0",
    "requests>=2.28.0",
    "tqdm>=4.64.0"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["pytest>=7.0.0"]
gpu = ["onnxruntime-gpu>=1.16.0"]

[project.urls]
Homepage = "https://github.com/yakhyo/uniface"
Repository = "https://github.com/yakhyo/uniface"

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = { find = {} }

[tool.setuptools.package-data]
"uniface" = ["*.txt", "*.md"]
